sudo: required

dist: trusty

language: node_js

node_js:
  - "7.2.1"

before_install:
  # for g++4.8 and C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # for solc
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev

  # solc setup
  - sudo apt-get update -y -qq
  - sudo apt-get install -yqq solc

install:
  - npm install

script: npm run compile && (npm run testrpc & ((sleep 5; npm run migrate && npm run test) ; killall npm))